### ISSUE TITLE
report-uri is deprecated in favor of report-to

### ISSUE THREAD

**Issue by connorshea** [github/secure_headers#269]
I don't know if the gem should be modified based on drafts of the spec, but I figured it was worth noting that the latest draft of the CSP standard replaces `report-uri` with `report-to` ([Source](https://w3c.github.io/webappsec-csp/#directive-report-uri)).

Obviously `report-uri` shouldn't be removed, but `report-to` might want to be supported? I'm not particularly familiar with the W3C drafting process, so I'm not sure how much of this will be subject to significant change.

**Comment by oreoshake** [comment]
This library has an unofficial policy of "we'll wait until we see it IRL". If anyone has implemented `report-to` I think it's safe to make some changes. Just like https://github.com/twitter/secureheaders/issues/260, then it becomes an issue of UA sniffing to determine support.

Does anyone support `report-to`?

**Comment by connorshea** [comment]
Fair enough, to my knowledge this isn't in any browsers as of yet. Feel free to close this issue.

**Comment by oreoshake** [comment]
I'll leave it around until it disappears from the draft spec :smile:

**Comment by connorshea** [comment]
@oreoshake maybe the wrong place to ask, but once I get a hang of using the secureheaders gem would you accept improvements to the documentation? e.g. a table with each parameter and their possible values? It's something I've been wanting while testing out the gem :)

**Comment by oreoshake** [comment]
I would gladly accept all documentation changes! 

I've been thinking about a `/docs` directory or enabling the wiki to help add more information in an organized way. The `README` is getting loooooong and such a table might warrant standing on its own.

**Comment by oreoshake** [comment]
😢  I can't enable the wiki because I'm not an admin :cry: @caniszczyk whom can I bother about this?

**Comment by connorshea** [comment]
Personally I'd prefer a `/docs` directory, but that's just me.

**Comment by Xosmond** [comment]
am i getting this?
The Content Security Policy 'plugin-types application/pdf' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.

**Comment by jacobbednarz** [comment]
@Xosmond nope - that means you're lacking a reporting directive in your report only policy.

**Comment by Xosmond** [comment]
@jacobbednarz but i have defined report_uri in config.csp an also in config.hpkp. So i don't know what more.

**Comment by jacobbednarz** [comment]
Do you have a link to a sample application demonstrating this behaviour that I could take a look at? Only other thing could be that it's getting trampled on by another piece of code but without the actual code, it will be difficult to find.

**Comment by oreoshake** [comment]
@Xosmond yeah, if you can provide your `SecureHeaders::Configuration.default` and any SecureHeaders::Configuration.override` calls it would be very helpful. 

Please file a separate issue. While it certainly appears related to this issue, I suspect it's not.

**Comment by oreoshake** [comment]
Blink has announced their intent to ship report-to support https://twitter.com/intenttoship/status/868025704432185344https://twitter.com/intenttoship/status/868025704432185344

**Comment by jacobbednarz** [comment]
@connorshea there is now a `docs` directory if you'd like to contribute that table 😄

**Comment by scottschup** [comment]
`report_to` is now supported in Chrome and Edge and several mobile platforms. Might be time to start thinking about reviving this task.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to#Browser_compatibility

**Comment by oreoshake** [comment]
This is still a good idea, but I'm going to be this will never change without GitHub's awareness. I would be more than happy to be wrong!
