### ISSUE TITLE
Add instructions for Rails 5 confusion? 

### ISSUE THREAD

**Issue by csuhta** [github/secure_headers#273]
Rails 5.0 includes [several header options](http://api.rubyonrails.org/classes/ActionDispatch/SSL.html) that conflict with Secure Headers 3.3.2.

For example, here is my SecureHeaders config:

``` ruby
SecureHeaders::Configuration.default do |config|
  config.cookies = {
    secure: true,
    httponly: true,
  }
  config.hsts = "max-age=#{356.days}"
  config.x_frame_options = "DENY"
  config.x_content_type_options = "nosniff"
  config.x_download_options = "noopen"
  config.x_permitted_cross_domain_policies = "none"
  config.x_xss_protection = "1; mode=block"
  config.referrer_policy = SecureHeaders::OPT_OUT
  config.csp = SecureHeaders::OPT_OUT
end
```

If I set `force_ssl = true` in the Rails configuration, I get this when I boot a Rails 5.0 app:

``` text
DEPRECATION WARNING: In Rails 5.1, The `:subdomains` option of HSTS config will be treated as true if unspecified. 
Set `config.ssl_options = { hsts: { subdomains: false } }` to opt out of this behavior.
```

It's unclear to the user (1) why they need to set it in both places (2) which one overrides the other. Also, should SecureHeaders be performing the Rails configuration for you?

**Comment by oreoshake** [comment]
@csuhta thank you for opening this. Must be nice running rails 5 😉 . When rails 4 introduced "default headers" [we added code to the railtie](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/railtie.rb#L13) that unsets these headers.

IMO if you are using secure_headers, the default rails behavior should be disabled. So it's just a matter of figuring out how to disable/override the rails 5 default behavior. I'm traveling over the next few weeks so I'd love it if someone could submit a PR to do so.

Upon a quick initial glance, secure_headers supports everything that rails does (at least for hsts and secure_cookies) and some more! Specifically, the samesite attribute on cookies.

**Comment by connorshea** [comment]
We'll be updating to Rails 5 soon (hopefully), so this'd be nice to have fixed :)

I guess the main thing here is making sure that if we disable the Rails behavior it doesn't mean that secure_headers doesn't also get overridden?

**Comment by Xosmond** [comment]
Problem here, i have this:
`  config.x_frame_options = "SAMEORIGIN"`
but the browser said that i have this:
`config.x_frame_options = "DENY"`
Where can i change it?

**Comment by oreoshake** [comment]
I haven't even looked at Rails 5 yet. @csuhta, you can temporarily work around this by setting ` force_ssl = false` (I think). 

If anyone with Rails 5 experience wants to chime in on disabling the rest, please do.

**Comment by csuhta** [comment]
Setting `force_ssl = false` will disable the entire `ActionDispatch::SSL` middleware, including the part that 301 redirects users onto `https` URLs. As far as I know, SecureHeaders doesn’t have this feature.

Looking at the code for `ActionDispatch::SSL`, there doesn't seem to be an easy way to disable only the header portions.

For future pull-requesters, your options seem to be:

- Monkeypatch `ActionDispatch::SSL` (don’t actually do this)
- After SecureHeaders parses its config and determines what the user wants, SecureHeaders should check for Rails 5 and configure the values of `Rails.application.config.ssl_options` for the user (probably the best option)
- After SecureHeaders parses its config and determines what the user wants, it should unseat the `ActionDispatch::SSL` middleware, and provide all of the same features. SecureHeaders already does everything ActionDispatch::SSL does except the redirect.

**Comment by oreoshake** [comment]
I think adding the redirect and unsetting the middleware would be the best option. It seems to be more inline with "if you're using secure_headers, the built-in rails behavior should be disabled".

**Comment by jimmybaker** [comment]
We've been on Rails 5 for a while now and just started using this gem in order to implement CSP. `force_ssl` doesn't work when using this gem and we had to write our own redirection method.

```
# force_ssl
before_action :redirect_to_ssl, unless: 'request.ssl?'
def redirect_to_ssl
  redirect_to protocol: :https
end
```

**Comment by oreoshake** [comment]
I believe all we'd need is to insert a redirect [here, before the `#call`](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/middleware.rb#L11).

**Comment by jimmybaker** [comment]
@oreoshake The stuff I posted earlier was incorrect. force_ssl does work with secure headers. I had forgotten that I had haproxy in front of our staging app and it was configured improperly which is what made me think it was this gem causing the problem.

**Comment by oreoshake** [comment]
Well, the redirect is still worth while IMO

**Comment by oreoshake** [comment]
With rails 7 on the horizon, I'm going to close this as an accepted hurdle.
