### ISSUE TITLE
Source Deduplication Doesn't Take Schemes into Account

### ISSUE THREAD

**Issue by belenko** [github/secure_headers#317]
`SecureHeaders` excessively deduplicates sources without taking schemes into account leading to removal of sources that shouldn't be removed.

I think the problem is with [`dedup_source_list()`](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/headers/content_security_policy.rb#L151) which relies on filesystem-like matching.

### Expected Header

`Content-Security-Policy: default-src 'self' wss://ws.contoso.com *.contoso.com`

### Actual Header

`Content-Security-Policy: default-src 'self' *.contoso.com`

### Config

```ruby
SecureHeaders::Configuration.default do |config|
  config.csp = {
    preserve_schemes: true, # this line doesn't matter, actually
    default_src: %w('self' wss://ws.contoso.com *.contoso.com)
  }
end
```

**Comment by oreoshake** [comment]
Welp. I'm assuming that policy mangling means your CSP is breaking functionality. The `*` should only apply to http/https schemes.

**Comment by belenko** [comment]
As a workaround we currently settled on `%w('self' wss://*.contoso.com *.contoso.com)` which works as expected, so not a deal breaker for us (though had to spend some time to figure out who eats that `wss://` source :) )

**Comment by oreoshake** [comment]
I've never been a fan of the deduplication based on `*` anyways. Maybe we should just rip that out.

**Comment by oreoshake** [comment]
Like people trying to save a few bytes can optimize elsewhere.

**Comment by vuthithanhbinh1220** [comment]
https://github.com/twitter/secureheaders/labels/bug

**Comment by srt32** [comment]
This should be resolved by https://github.com/github/secure_headers/pull/478

**Comment by lgarron** [comment]
Source deduplication was removed in https://github.com/github/secure_headers/pull/499
