### ISSUE TITLE
Cross-Origin Resource Sharing (CORS)

### ISSUE THREAD

**Issue by somethingnew2-0** [github/secure_headers#331]
This is more of a question than a feature request, is there a historical reason the Cross-Origin Resource Sharing (CORS) headers aren't included in the list of headers configured by secureheaders?  Has it just not been implemented yet? Do you all recommend using [rack-cors](https://github.com/cyu/rack-cors) as a complement to secureheaders instead of including this feature directly? Just curious 😄

**Comment by oreoshake** [comment]
> Has it just not been implemented yet? 

It hasn't even been discussed from what I can tell or remember.

### History 💤 

> is there a historical reason the Cross-Origin Resource Sharing (CORS) headers aren't included in the list of headers configured by secureheaders?

My guess would be that CORS is flat out *required* for a lot of things on the internet today. Building on top of that, more people have experience configuring CORS and more *providers* have configuration APIs/configs/etc.

e.g. AWS has supported CORS for years and [provides a way to set values](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors), but makes it a pain to [enable hsts(and apparently has only recently started supporting it)](https://forums.aws.amazon.com/thread.jspa?threadID=162252).

This library set out as a way to apply headers that were **optional** and often overlooked. 

📖 💤 😴 

### Present ⌚️ 

I haven't used `rack-cors` but maybe @ejcx has or has an opinion? 

### Future :rocket:

I could see this living in `secure_headers`.

**Comment by ejcx** [comment]
Hey @oreoshake thanks for the ping. rack-cors actually has a fundamental problem that I wrote about almost a year ago.

One thing to look out for is libraries that reflect an origin header when you specify an Access-Control-Allow-Origin policy of "*". "*" should be "*".

**Comment by oreoshake** [comment]
I'm going to take the possibly unpopular opinion and saying that CORS is too application specific to be handled by this library given the alternatives. 

I welcome all opinions counter to this proposal but stale issue should be closed.

**Comment by ejcx** [comment]
That's fair @oreoshake
