### ISSUE TITLE
Remove auto-insertion of middleware and force the manual insertion to avoid whacky bugs

### ISSUE THREAD

**Issue by edwinv** [github/secure_headers#349]
We are using SecureHeaders 3.6.7 in a Rails 5.0.3 project and want to start using the `nonced_javascript_tag` helper to remove `unsafe-inline` from our CSP.

### Expected outcome

When using the `nonced_javascript_tag`, we expect two things:

1. A `script` tag with a `nonce` attribute
2. A `nonce-...` value in our CSP header

### Actual outcome

1. `script` tag is correct
2. `nonce-...` value is missing from the CSP header

### Config

```
# frozen_string_literal: true

::SecureHeaders::Configuration.default do |config|
  config.x_frame_options = "DENY"
  config.x_content_type_options = "nosniff"
  config.x_xss_protection = "1; mode=block"

  config.csp = {
    default_src: %w['none'],
    connect_src: %w['self' www.project.nl],
    child_src: [Rails.application.secrets.applications["storage_public_url"]],
    img_src: ["'self'", "data:", Rails.application.secrets.applications["storage_public_url"], Rails.application.secrets.applications["assets"]],
    style_src: ["'self'", Rails.application.secrets.applications["assets"], "'unsafe-inline'"],
    font_src: ["'self'", Rails.application.secrets.applications["assets"]],
    script_src: ["'unsafe-eval'", Rails.application.secrets.applications["assets"]],
    object_src: %w['none'],
    media_src: %w['none'],
    frame_ancestors: %w['none'],
    report_uri: %w[/csp_report]
  }

  config.hsts = SecureHeaders::OPT_OUT
end
```

### Generated headers

```
Cache-Control:no-cache, no-store, must-revalidate
Connection:keep-alive
Content-Length:35584
Content-Security-Policy:default-src 'none'; child-src storage.project.dev app.project.dev; connect-src 'self' www.project.nl; font-src 'self' assets.project.dev; frame-ancestors 'none'; img-src 'self' data: storage.project.dev assets.project.dev; media-src 'none'; object-src *; script-src 'unsafe-eval' assets.project.dev 'self'; style-src 'self' assets.project.dev 'unsafe-inline'; report-uri /csp_report
Content-Type:text/html; charset=utf-8
Date:Wed, 16 Aug 2017 10:58:28 GMT
Expires:0
Pragma:no-cache
Server:nginx/1.4.6 (Ubuntu)
X-Content-Type-Options:nosniff
X-Download-Options:noopen
X-Frame-Options:ALLOW-FROM https://app.project.dev
X-Permitted-Cross-Domain-Policies:none
X-Request-Id:d748d1d5-b6c3-42f6-8b41-6d088ee8283a
X-XSS-Protection:1; mode=block
```

### Debugging

I've done some debugging to find out if the problem was in another part of our software. I came to the following conclusions:

1. Calling the `nonced_javascript_tag` helper, indeed sets the `nonce` in the SecureHelper configuration. 
2. This nonce is still present at the end of the request in Rails, tested by reading the `request.env['secure_headers_request_config']` in an `after_action` callback in the `ApplicationController`.
3. When the SecureHeaders middleware kicks in, `env['secure_headers_request_config']` is nil, therefore a new default configuration is loaded from our configuration in `config/initializers/secure_headers.rb`. Somehow the configuration already stored in the `env` is neglected, therefore the nonce is missing and not added to the headers.

I've disabled all custom middleware in our project to make sure our middleware isn't interfering with the `env` object, this didn't have any impact on the result.

**Comment by edwinv** [comment]
After debugging a bit more, I found out that `Rack::Lock` was removing the value from the environment. It seems that this commit solves this issue: https://github.com/rack/rack/commit/7fa67d8c02719b67f792eae2f1024c6b64a804ba

Maybe it is safer to add the secure headers middleware somewhere a bit higher in the stack instead of position 0 to be less vulnerable for errors in other middleware?

**Comment by oreoshake** [comment]
Ouch. This would also completely break the other dynamic features (append/override) entirely.

> Maybe it is safer to add the secure headers middleware somewhere a bit higher in the stack instead of position 0 to be less vulnerable for errors in other middleware?

So what should https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/railtie.rb#L14 become? It appears the insertion point is important to [cookie related behavior](https://github.com/twitter/secureheaders/pull/231#r56240744). The way railties/middlewares get loaded when using the `secure_headers` railtie has always been somewhat nebulous to me.

I've always wondered how this worked for others since I've always manually included middlewares so the insertion point has always been highly specific. For example, we have a few middlewares that *must* run before `secure_headers` and the `secure_headers` middleware must be early enough to catch application errors (don't ask). 

The automatic insertion of the middleware is nice and makes adoption easier, but if it's causing problems then maybe it's worth adding a blurb to the `README` and remove the `railtie`. If you don't use the middleware, nothing will happen and I'm pretty sure people will figure out what needs to happen.

What do you think @edwinv?

**Comment by edwinv** [comment]
Automatic insertion of the middleware is also irreversible if you want to use the Rails way to manage your middleware. After finding the bug, my initial thought was to move `secure_headers` before `Rack::Lock` to fix the issue:

```
config.middleware.delete SecureHeaders::Middleware
config.middleware.insert_after Rack::Lock, SecureHeaders::Middleware
```

This doesn't work because `config.middleware` is a Rails proxy for the middleware stack and only records the actions you perform on them before executing them. So the first line is executed last, therefore removing the `secure_headers` middleware altogether instead of only the first instance.

Although I like gems that don't require much configuration, I think it also good for developers to know what they are doing and what they are adding to their project. Making this a specific configuration for `secure_headers` seems like a good way to go.

Maybe you can even check the middleware stack when a user uses `SecureHeaders::Configuration.default` to check if the middleware is included and raise an error otherwise? Depends a bit on the load order of things maybe, but would make a great extra nudge for starters.

**Comment by oreoshake** [comment]
> Depends a bit on the load order of things maybe, but would make a great extra nudge for starters.

I *think* it's safe to assume people configure middlewares before initializers. (For people using secure_headers for the first time) I just wonder if it's fine to say if you didn't get your headers, you either didn't read the (simple) instructions or you didn't test a thing. If you're upgrading, especially in this release, you're probably already dealing with other breaking changes in this major release.

What's interesting is that `secure_headers` 4.0 still hasn't dropped so if we wanted to add *breaking* behavior, now would be a great time to do so. Given it's potential to break many simpler installations, it might be better to remove in 5.0.

I'm :100: :+1: on removing the auto-insertion eventually.

**Comment by oreoshake** [comment]
I'm fairly settled on punting on this until 5.x. A through deprecation period seems to be necessary as the failure case is that zero protection is applied from a library that preaches "secure by default."

**Comment by oreoshake** [comment]
While the current, and historical, approach may not be ideal, this issue has gone stale. Rails and secure_headers have had a few interoperability issues that have been addressed, but this one seems to affect fewer applications.
