### ISSUE TITLE
bundler_audit found vulnerability in both v3.8.0 and v3.9.0

### ISSUE THREAD

**Issue by marinfr** [github/secure_headers#424]
We encountered a problem this morning when running our pipelines.
`bundler-audit` (v0.6.1) notified about a vulnerability found in `secure_headers` (v3.6.7) and suggested to upgrade to `3.8.0` or `3.9.0`. We updated to `3.8.0` first and it said to update to `3.9.0`:

![](https://i.imgur.com/P8sO6fq.png)

After updating to `3.9.0` it asked to downgrade back to `3.8.0`:

![](https://i.imgur.com/bx4x0PT.png)

Is this a bug in `secure_headers` or `bundler-audit`? Is it safe to ignore the advisory?

P.S. - Is there a reason I can't find `3.9.0` tag in the repository?

**Comment by buraga-dmitrii** [comment]
We have the same problem

**Comment by oreoshake** [comment]
It’s very possible that I didn’t do the advisory correctly. I’ll look into the missing tag. 

I don’t know much about bundled-audit but 3.8 is not what you want. 

I’d be very grateful if an adult could help me right this, assuming this isn’t an issue with bundles-audit

**Comment by Edmuund** [comment]
@oreoshake so until you fix the advisory it should be safe to use 3.9 and ignore the vulnerability alert right?

**Comment by oreoshake** [comment]
> @oreoshake so until the advisory is fixed it should be safe to use 3.9 and ignore the vulnerability alert right?

I believe that is correct.

**Comment by jacobbednarz** [comment]
This looks to be an issue in bundler-audit. There is already rubysec/ruby-advisory-db#428 open to address fixing the version constraints.

**Comment by Goltergaul** [comment]
Hi those two issues are mutually exclusive (~> 3.8.0 and ~> 3.9.0) so installing either one still fails the other security vulnerability

**Comment by oreoshake** [comment]
> i believe the security fix constraints on this one need to be adapted accordingly GHSA-xq52-rv6w-397c

Thanks @Goltergaul. Before I go and muck this up again, can someone sanity check me that `>= 6.2.0, >= 5.1.0, >= 3.8.0` will make everything happy? I suppose I should apply the same reasoning to https://github.com/twitter/secure_headers/security/advisories/GHSA-w978-rmpf-qmwg as well.

**Comment by oreoshake** [comment]
I’ve pushed the 3.9.0 tag

**Comment by Goltergaul** [comment]
I'm not 100% sure how bundle-audit handles those version, but here they suggested something different: https://github.com/rubysec/ruby-advisory-db/issues/428

**Comment by oreoshake** [comment]
I’ve updated the fixed versions (twice) so I think it’s correct. I have no idea how this gets pushed into other systems 🤷‍♂
