### ISSUE TITLE
secure_headers is moving!

### ISSUE THREAD

**Issue by kaoudis** [github/secure_headers#426]
secure_headers source code (this repository) will shortly be transferred from the Twitter GitHub organization to GitHub's GitHub organization. @oreoshake **will** continue as maintainer; also issue history, forks, etc should be preserved with the transition (basically, nothing should change except the repo location here on GitHub). Links on rubygems.org will be updated following the transition to point to the new GitHub location.

More about repository transfers (what we're planning on doing): https://help.github.com/en/github/administering-a-repository/transferring-a-repository

If you have any questions, feel free to comment here for the next week or so, after which we’ll lock the thread.

Thanks for all your hard work and your contributions over the years!
@agargenta, @kaoudis, @oreoshake

**Comment by oreoshake** [comment]
It's done!
