### ISSUE TITLE
CSP ["https://*"] or ["http://*"] will be transferred to ["*"]

### ISSUE THREAD

**Issue by zhengxiangyue** [github/secure_headers#434]
# Bugs

### Expected outcome

1. I configure CSP 3.9.0 to **allow loading resource from https sites**. I'm not expert of CSP or wildcard matching rules. But it looks not right to me when it converts to "*"

```
::SecureHeaders::Configuration.default do |config|
  config.x_frame_options = 'SAMEORIGIN'
  config.x_content_type_options = "nosniff"
  config.x_xss_protection = "1; mode=block"
  config.csp = {
    default_src: ['https://*']
  }
```

1. The CSP should have included 
```
Content-Secure-Policy: default-src https://*
```

### Actual outcome

1. The generated policy did not include `https://*`
```
Content-Secure-Policy: default-src *
```

### Config

Shown as above

### Generated headers

Shown as above

### Investigation

![Screen Shot 2020-03-11 at 10 05 32 PM](https://user-images.githubusercontent.com/18232408/76483226-741d6c00-63e4-11ea-8689-43e696b242cd.png)

Please let me know if this is expected and if I miss something. Thanks! This wasn't occurring in version `1.2.0`

**Comment by jacobbednarz** [comment]
You're probably wanting `https:` here, not `https://*`. Check out the [w3c webappsec spec for CSP level 2](https://w3c.github.io/webappsec-csp/2/) for valid directives and their values.

**Comment by jacobbednarz** [comment]
You can check the validity (and any pitfalls) of your policy at https://csp-evaluator.withgoogle.com/.

**Comment by zhengxiangyue** [comment]
Cool, make perfect sense to me. Thanks 👍
