### ISSUE TITLE
Ignoring CSP on some formats

### ISSUE THREAD

**Issue by paul-mesnilgrente** [github/secure_headers#437]
# Feature Requests

I found a bug of display of PDFs in Chrome. See https://bugs.chromium.org/p/chromium/issues/detail?id=271452

Would it possible to disable CSP on every .pdf for example?

**Comment by oreoshake** [comment]
I think there are a couple ways to accomplish this. Forgive me, this is a bit pseudo-code-ey.

```ruby
before_action :no_csp_plz

SecureHeaders::Configuration.override(:no_csp) do |config|
  config.csp = SecureHeaders::OPT_OUT
end

def no_csp_plz
  if content type is pdf
    use_secure_headers_override(:no_csp)    
  end
end
```

Or

```ruby
before_action :no_csp_plz

def no_csp_plz
  if content type is pdf
    opt_out_of_header(:csp)
  end
end
```

If I had to pick, I'd say the first option is more idiomatic. 

You can probably move that `if` to the `before_action` declaration.
