### ISSUE TITLE
how to allow all iframe for any sites?

### ISSUE THREAD

**Issue by RohitVenturit** [github/secure_headers#438]
how to allow all iframe for any sites?
I am trying to add site to allow visible in iframe in my rails v 4.1.2 application.
config.action_dispatch.default_headers.clear does not work. Can anyone please help me?

**Comment by oreoshake** [comment]
What is the csp being served? `frame_src: [“*”]` should be all that you need, assuming the sites allow themselves to be framed. 

Console errors would be really helpful too.
