### ISSUE TITLE
CSP and google tag manager

### ISSUE THREAD

**Issue by mateo9** [github/secure_headers#447]
I have requirement to remove 'unsafe-inline' and 'unsafe-eval from script_src. However I use Google Tag Manager in application.
After some research I found that I need allow 'unsafe-inline' and 'unsafe-eval' to GTM work properly. (https://www.simoahava.com/analytics/google-tag-manager-content-security-policy/). Google Tag Manager is a script injector. Is any workaround to allow 'unsafe-inline' and 'unsafe-eval' only for GTM?

**Comment by oreoshake** [comment]
> I have requirement to remove 'unsafe-inline' and 'unsafe-eval from script_src. However I use Google Tag Manager in application.

Hi @mateo9, from what I can tell that's not possible but I don't have any experience in the matter. https://developers.google.com/tag-manager/web/csp says you can use a nonce to remove the `unsafe-inline` requirement, but `unsafe-eval` is required for "Custom JavaScript Variables" which it sounds like you're using.
