### ISSUE TITLE
Setting SameSite cookie attribute conditionally

### ISSUE THREAD

**Issue by arashb31** [github/secure_headers#459]
Is there a way to be able to set the SameSite=None or SameSite=Strict conditionally in a controller action?
For example, if current_user.admin?, upgrade the session_store cookie with SameSite=Strict, otherwise, keep it as None.

**Comment by oreoshake** [comment]
@arashb31 There is a way! In fact, it's probably the best way to retroactively roll out samesite in general.



```ruby
SecureHeaders::Configuration.override(:admin_hardening) do |config|
  config.cookies = {
    samesite: {
      strict: { only: ["my_admin_cookie"] },
      none: { only: ["saml_csrf_token", "saml_return_to"] },
      lax: { except: ["my_admin_cookie", "saml_csrf_token", "saml_return_to"] },
    },
  }
end
```

```ruby
# you'll want to do this as early as possible as you would lose 
# any modifications to the config to this point (append/override_content_security_policy_directives)
def some_before_action
  if admin?
    use_secure_headers_override(request, :admin_hardening)
  end
end
```

What I can't recall is if you'd need to copy over whatever other cookie settings or if you only need to supply the modifications. I suspect you'd need to duplicate the config (or read from `config.cookies`)

**Comment by arashb31** [comment]
Wow that worked very nicely!
One unexpected side effect was that a lot of other headers were set that I was not expecting.
I'm guessing the gem sets a default hardening. Is there a way to disable all those default hardenings?

**Comment by oreoshake** [comment]
There was an example of someone doing this recently: https://github.com/github/secure_headers/issues/450

There isn't a single-line config option but you can turn off the safe defaults using that strategy.

**Comment by arashb31** [comment]
Thanks so much. Appreciate the help, and an excellent gem!
