### ISSUE TITLE
Major Version 7.0.0

### ISSUE THREAD

**Issue by JackMc** [github/secure_headers#480]
## Summary

It came up in https://github.com/github/secure_headers/pull/479 that we should start brainstorming the features for a new major version of Secure Headers. This is a holding issue for features and PRs that could be merged if we were able to make breaking changes.

## PRs

* https://github.com/github/secure_headers/pull/479
* https://github.com/github/secure_headers/pull/422

## Ideas

* https://github.com/github/secure_headers/issues/482

**Comment by KyFaSt** [comment]
@JackMc will set a meeting time for our team to go through the issue backlog and decide what should be included.
