### ISSUE TITLE
Remove non necessary files from bundled Ruby Gem

### ISSUE THREAD

**Issue by rzhade3** [github/secure_headers#531]
The current bundled Rubygem contains all the files in this directory, bloating the size of the gem and causing unnecessary changes when the only update to this repo was a Actions configuration update.

We should instead update the `.gemspec` to only bundle necessary files into the gem. This should be done by updating this line: https://github.com/github/secure_headers/blob/b134eef07d3741b4bd0769b863961b41af5df57d/secure_headers.gemspec#L18

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
